question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Television",
     "question": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
     "question": "There is a Donald Trump Board Game, which was made in 1989.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In the video game &quot;Splatoon&quot;, the playable characters were originally going to be rabbits instead of squids.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
     "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Board Games",
     "question": "Snakes and Ladders was originally created in India?", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                                       "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Animals",
     "question": "A flock of crows is known as a homicide.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Mythology", "question": "A wyvern is the same as a dragon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Politics",
     "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
